/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: person-x (https://sketchfab.com/person-x)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/gray-fox-7313f22ffe3945cf83445d1bc3860d73
title: Gray Fox
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from 'react-three-fiber'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene.gltf')
  const { actions } = useAnimations(animations, group)
  useFrame(({ mouse }) => {
    group.current.rotation.y = group.current.rotation.y -= 0.004
    group.current.position.x =  -(mouse.y * 0.08)

  })
  return (
    <group ref={group} {...props} dispose={null} position={[0.6,0,0]}>
      <group rotation={[-Math.PI / 2, -0.5, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group name="Armature" rotation={[0, 0, 0]}>
            <primitive object={nodes._rootJoint} />
            <skinnedMesh
              geometry={nodes['SU-Blade_Tsuka__0'].geometry}
              material={materials.Tsuka}
              skeleton={nodes['SU-Blade_Tsuka__0'].skeleton}
            />
            <skinnedMesh
              geometry={nodes['SU-Blade_Tsuba__0'].geometry}
              material={materials.Tsuba}
              skeleton={nodes['SU-Blade_Tsuba__0'].skeleton}
            />
            <skinnedMesh
              geometry={nodes['SU-Blade_Habaki__0'].geometry}
              material={materials.Habaki}
              skeleton={nodes['SU-Blade_Habaki__0'].skeleton}
            />
            <skinnedMesh
              geometry={nodes['SU-Blade_Blade_0'].geometry}
              material={materials.Blade}
              skeleton={nodes['SU-Blade_Blade_0'].skeleton}
            />
            <skinnedMesh
              geometry={nodes['SU-Blade_The_edge_of_Blade_0'].geometry}
              material={materials.The_edge_of_Blade}
              skeleton={nodes['SU-Blade_The_edge_of_Blade_0'].skeleton}
            />
            <skinnedMesh
              geometry={nodes.Ninja_Cyborg_Cube_Gfox_0.geometry}
              material={materials.Gfox}
              skeleton={nodes.Ninja_Cyborg_Cube_Gfox_0.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
