import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Navbar } from '../components/Header/Navbar'
import { useOnScreen } from '../components/Triggers/Observers'
import { Cover } from '../components/Content/Cover'

export default function Home() {
  const [setRef, visible] = useOnScreen({ threshold: 0.1})
  return (
    <div className={styles.container}>
      <Head>
        <title>Adazolhub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


       <div className={styles.wrapper}>
       <Navbar 
        navBG={visible? 'rgba(255, 255, 255, 0.01)' : 'var(--gray-dark)'}
        navColor={visible? '#2ACB9D' : '#43434D'}
        testClass={visible}
        />
         <section className={styles.section} ref={setRef}>
            <div className={styles.cover}>
              <Cover/>
            </div>
         </section>
         <section 
            
            className={styles.section}  
            style={{ 
                    background: visible? 'var(--gray-dark)' : 'var(--gray-500)',
                    color: visible? '#6D6D7A' : '#CDCDD1'
                }}>
            Section 1
         </section>
         <section className={styles.section}>
            Section 2
         </section>
         <section className={styles.section} >
            Section 3
         </section >
         <section className={styles.section}>
           <button >Test</button>
         </section>
       </div>



    </div>
  )
}
